### PR TITLE
Bump minio version

### PR DESCRIPTION
**Pull request by pennyscissors**
Bump minio version in tools_system_images

**Related Issues:**
rancher/rancher#27467

**Related PR's:**
https://github.com/rancher/types/pull/1169

### CODE REVIEW

**Review by aiyengar2 — DISMISSED** [review]
LGTM

**Review by prachidamle — COMMENTED** [review]
I see few more recent tags/releases under https://github.com/minio/minio/tags

Dont we want to update to the latest?

**Comment by pennyscissors** [comment]
@prachidamle I didn't realize updates would be available that quickly, the one here was the latest available at the time. Should I update it to the current latest, re-test it, and update this PR?

**Comment by prachidamle** [comment]
@PennyScissors yeah, I think we should get the latest and re-test

**Comment by pennyscissors** [comment]
@prachidamle @aiyengar2 Just updated to latest tag

**Review by prachidamle — APPROVED** [review]
LGTM

**Pull request merged**
