### PR TITLE
Add sasl support for logging kafka

### PR DESCRIPTION
**Pull request by aiwantaozi**
Add sasl support for logging kafka

Problem:
need support sasl auth for kafka logging

Solution:
add sasl support

Issue:
https://github.com/rancher/rancher/issues/16614

### CODE REVIEW

**Comment by loganhz** [comment]
@fyery-chen please review it. thanks

**Comment by fyery-chen** [comment]
LGTM

**Comment by cjellick** [comment]
LGTM

**Comment by cjellick** [comment]
Closing in favor of https://github.com/rancher/rancher/pull/17542, which is the same except that I updated vendor.conf appropriately

**Pull request merged**
