### PR TITLE
Add multiarch support using docker manifest

### PR DESCRIPTION
**Pull request by jianghang8421**
This PR includes the following changes.
- Update k8s `1.12.6` and `1.13.4` images to use docker manifest

`1.11.8` can not support ARM64 because `nginx-ingress-controller:0.16.2-rancher1` is not supporting the ARM64 platform.

Issue
https://github.com/rancher/rancher/issues/16461

### CODE REVIEW

**Comment by loganhz** [comment]
LGTM

**Comment by loganhz** [comment]
We need to run [this script](https://github.com/jianghang8421/publish-manifest/blob/master/publish-manifest-images.sh) to push the related manifest images

**Comment by loganhz** [comment]
Please close this PR. Created another PR to address it.

**Comment by loganhz** [comment]
LGTM

**Comment by loganhz** [comment]
Please close it

**Comment by jianghang8421** [comment]
Close

**Pull request closed without merging**
