### PR TITLE
Bump Jenkins version

### PR DESCRIPTION
**Pull request by gitlawr**

### CODE REVIEW

**Comment by cjellick** [comment]
lgtm but its a draft pr so i cannot merge it

**Comment by cjellick** [comment]
I made the tag https://github.com/rancher/pipeline-jenkins-server/releases/tag/v0.1.1
but it looks like that repo isnt setup to use drone to build images because I do not see one getting built.
Please update it so that drone can build the images. We should be building any productions images on our personal computers any more.

**Comment by gitlawr** [comment]
Drone file is present in that repo. the image can be published if the repo is activated in drone server.

**Comment by loganhz** [comment]
`rancher/pipeline-jenkins-server:v0.1.2` is out

**Comment by gitlawr** [comment]
Plugin dependency breaks, need a fix for it: https://github.com/rancher/pipeline-jenkins-server/pull/5

**Comment by gitlawr** [comment]
Need a new release of `rancher/pipeline-jenkins-server` image

**Comment by loganhz** [comment]
v0.1.3 image released

**Comment by gitlawr** [comment]
Ready for merge

**Pull request merged**
