### PR TITLE
Gitlab support in pipeline

### PR DESCRIPTION
**Pull request by gitlawr**
Related issue: https://github.com/rancher/rancher/issues/12608

### CODE REVIEW

**Comment by zionwu** [comment]
LGTM

**Comment by aiwantaozi** [comment]
LGTM

**Comment by mikolajkomisarek** [comment]
When gitlab support(pipeline) will be shared to master or latest?

**Comment by BalaBalaYi** [comment]
Same .... When gitlab support will be merged to master?

**Comment by thelinuxlich** [comment]
Please this is a amazing feature!

**Comment by myselfghost** [comment]
Same .... When gitlab support will be merged to master?

**Comment by alena1108** [comment]
Closing as gitlab support is added as a part of bigger refactoring for pipeline feature.

**Pull request closed without merging**
