### PR TITLE
Added redeploy to workload api actions

### PR DESCRIPTION
**Pull request by shanewxy**
Added redeploy API to workload which set the timestamp to the current time.

Related issue: https://github.com/rancher/rancher/issues/23053

### CODE REVIEW

**Comment by gitlawr** [comment]
Are deployments working with this pr?
Do we need to update the following block as well: https://github.com/rancher/types/blob/2acfcad7d968bb7d92d6d054d77106016a1df3b7/apis/project.cattle.io/v3/schema/schema.go#L466-L474

**Comment by gitlawr** [comment]
Can you squash the first two commits

**Comment by shanewxy** [comment]
rebased

**Comment by loganhz** [comment]
Rancher PR has been approved https://github.com/rancher/rancher/pull/24777

**Pull request merged**
