### PR TITLE
Bump minio version

### PR DESCRIPTION
**Pull request by pennyscissors**
Bump minio version is tools_system_images

Related Issue: rancher/rancher#27467

### CODE REVIEW

**Comment by maggieliu** [comment]
related to: https://github.com/rancher/rancher/issues/27467

**Review by aiyengar2 — APPROVED** [review]
LGTM, we should make sure this also gets ported to rancher/rancher as part of the changes by @ibuildthecloud

**Review by dramich — CHANGES_REQUESTED** [review]
This change needs to be made in rancher and I would guess a 2nd PR is still needed here for 2.4 branch.

**Comment by pennyscissors** [comment]
@dramich I just made the changes in `rancher/rancher` and `rancher/types` branch `release/2.4` and created new PR's. Let me know if there is anything else that I need to do. Thanks.

rancher: https://github.com/rancher/rancher/pull/27914
2.4: https://github.com/rancher/types/pull/1171

**Comment by pennyscissors** [comment]
Closed in favor of the following PR's as `rancher/types` is no longer used.
rancher: https://github.com/rancher/rancher/pull/27914
v2.4: https://github.com/rancher/types/pull/1171

**Pull request closed without merging**
