### PR TITLE
Support local chart app upgrade & rollback

### PR DESCRIPTION
**Pull request by thxCode**
**Problem:**
- Cannot upgrade local chart app
- Cannot rollback local chart app

**Solution:**
- Add `Files` field to `AppUpgradeConfig`
- Add `Files` field to `AppRevisionStatus` to record local chart templates

**Issue:**
rancher/rancher#15711

### CODE REVIEW

**Comment by gitlawr** [comment]
Why do we need the `ChartInfo` field. Given that it is only used for displaying info in cli, I think we can get that info from Chart.yml file in the `Files`

**Comment by thxCode** [comment]
@gitlawr , I have removed `ChartInfo` field, using `App.Spec.ExternalID` `App.Status.AppRevisionID` -> `AppRevision` to get the info from `Chart.yaml`

**Comment by gitlawr** [comment]
LGTM

**Comment by cjellick** [comment]
LGTM

**Comment by thxCode** [comment]
@cjellick , rebased

**Pull request merged**
