### PR TITLE
Add use tls config for syslog logging target

### PR DESCRIPTION
**Pull request by aiwantaozi**
Problem:
can't identify whether the syslog target use tls or not

Solution:
add enable tls field

Issue:
https://github.com/rancher/rancher/issues/15380

### CODE REVIEW

**Comment by orangedeng** [comment]
LGTM

**Comment by aiwantaozi** [comment]
rebased

**Comment by cjellick** [comment]
LGTM

**Comment by cjellick** [comment]
types PR merged. need a PR for rancher/rancher

**Pull request merged**
