### PR TITLE
add istio metrics graph types

### PR DESCRIPTION
**Pull request by fyery-chen**
`istiocluster` -- get istio metric information in cluster level
`istioproject` -- get istio metric information in project level

### CODE REVIEW

**Comment by orangedeng** [comment]
LGTM

**Comment by loganhz** [comment]
Link to https://github.com/rancher/rancher/issues/19087

**Comment by orangedeng** [comment]
Closing this PR in favor of PR https://github.com/rancher/types/pull/839

**Comment by loganhz** [comment]
Please close this PR

**Pull request closed without merging**
