### PR TITLE
Update Ingress controller version

### PR DESCRIPTION
**Pull request by orangedeng**
Related issue https://github.com/rancher/rancher/issues/15163
For k8s v1.12.3-rancher1-1, update ingress to 0.21.0-rancher1

Waiting for new Ingress controller image being built and pushed

### CODE REVIEW

**Comment by orangedeng** [comment]
Related ingress-nginx PR: https://github.com/rancher/ingress-nginx/pull/15

**Comment by alena1108** [comment]
@orangedeng can we update the version for 1.12.5 and 1.13?

**Comment by orangedeng** [comment]
Updated, version `v1.13.1-rancher1-1` is already using `rancher/nginx-ingress-controller:0.21.0-rancher1`. I only updated version `v1.12.5-rancher1-1`

**Comment by alena1108** [comment]
LGTM

**Pull request merged**
